// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegurosApp.Infrastructure;

#nullable disable

namespace SegurosApp.Api.Migrations
{
    // Eliminado: migración obsoleta. Regenerar con el nuevo DbContext de Infrastructure.
}
