//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSegurosFpDaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Poliza = new HashSet<Poliza>();
        }
    
        public int clienteId { get; set; }
        public string nombreCliente { get; set; }
        public string apellido1Cliente { get; set; }
        public string apellido2Cliente { get; set; }
        public string dniCliente { get; set; }
        public string emailCliente { get; set; }
        public string telefonoCliente { get; set; }
        public int activo { get; set; }
        public Nullable<System.DateTime> fechaDesactivado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poliza> Poliza { get; set; }
    }
}
