//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSegurosFpDaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionPoliza
    {
        public int gestionPolizaId { get; set; }
        public string matricula { get; set; }
        public string marcaVehiculo { get; set; }
        public string modeloVehiculo { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int precio { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fechaGestion { get; set; }
        public int condicionadoPolizaId { get; set; }
        public int tipoGestionId { get; set; }
        public int polizaId { get; set; }
        public int usuarioId { get; set; }
    
        public virtual CondicionadoPoliza CondicionadoPoliza { get; set; }
        public virtual Poliza Poliza { get; set; }
        public virtual TipoGestion TipoGestion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
