//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSegurosFpDaw.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoSegurosDbEntities : DbContext
    {
        public ProyectoSegurosDbEntities()
            : base("name=ProyectoSegurosDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CondicionadoPoliza> CondicionadoPoliza { get; set; }
        public virtual DbSet<GestionPoliza> GestionPoliza { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Poliza> Poliza { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolPermiso> RolPermiso { get; set; }
        public virtual DbSet<TipoGestion> TipoGestion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
