//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSegurosFpDaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.GestionPoliza = new HashSet<GestionPoliza>();
        }
    
        public int usuarioId { get; set; }
        public string nombreUsuario { get; set; }
        public string apellido1Usuario { get; set; }
        public string apellido2Usuario { get; set; }
        public string dniUsuario { get; set; }
        public string emailUsuario { get; set; }
        public string password { get; set; }
        public int activo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public int rolId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionPoliza> GestionPoliza { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
